version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd ci-cd # change directory
      - chmod +x install-terraform.sh configured-named-profile.sh apply-terraform.sh # make files executable
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - ./apply-terraform.sh






      
# the buildspec file contains the commands to codebuild will use to build 
# google buildspec.yml and select aws documentation to see the syntax
# python runtime used
# 3 phases : install - configure named profile - apply terraform